[tool.poetry]
name = "linked-data-repository"
version = "0.1.0"
description = ""
authors = ["mikeAdamss <mikelovesbooks@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.9"

[tool.poetry.dev-dependencies]
behave = "^1.2.6"
pytest = "^6.2.5"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
